"""Compatibility facade for the durable fixed-run Task event stream."""

from ruyi_agent.runtime.task_event_contracts import (
    DEFAULT_EVENT_BATCH_SIZE,
    DEFAULT_MAX_PENDING_DELTAS,
    DEFAULT_TAIL_POLL_SECONDS,
    MAX_ARTIFACT_CAPTION_JSON_BYTES,
    MAX_ARTIFACT_LIST_JSON_BYTES,
    MAX_ASSISTANT_DELTA_TEXT_LENGTH,
    MAX_DURABLE_TASK_EVENT_DATA_BYTES,
    MAX_EVENT_ARTIFACTS,
    MAX_EVENT_TEXT_LENGTH,
    MAX_LIFECYCLE_TEXT_JSON_BYTES,
    MAX_PENDING_REVIEW_JSON_BYTES,
    MAX_REVIEW_DECISIONS,
    MAX_REVIEW_ITEMS,
    MAX_SHORT_EVENT_TEXT_JSON_BYTES,
    MAX_SHORT_EVENT_TEXT_LENGTH,
    MAX_TASK_EVENT_CURSOR_LENGTH,
    PUBLIC_ASSISTANT_DELTA_NODES,
    PUBLIC_ASSISTANT_DELTA_PATH,
    TASK_EVENT_CURSOR_VERSION,
    TERMINAL_EVENT_TYPES,
    InvalidTaskEventCursorError,
    TaskEventsUnavailableError,
    TaskLifecycleEventType,
    TaskRunMismatchError,
    TaskStreamEvent,
)
from ruyi_agent.runtime.task_event_cursor import (
    decode_task_event_cursor,
    encode_task_event_cursor,
)
from ruyi_agent.runtime.task_event_ledger import (
    TaskEventLedger,
    TaskEventSubscription,
)
from ruyi_agent.runtime.task_event_projection import (
    artifact_event_data,
    assistant_delta_from_stream_part,
    lifecycle_event_data,
    lifecycle_event_type,
    normalize_task_event_text,
    public_task_event_fingerprint,
)

__all__ = [
    "DEFAULT_EVENT_BATCH_SIZE",
    "DEFAULT_MAX_PENDING_DELTAS",
    "DEFAULT_TAIL_POLL_SECONDS",
    "MAX_ARTIFACT_CAPTION_JSON_BYTES",
    "MAX_ARTIFACT_LIST_JSON_BYTES",
    "MAX_ASSISTANT_DELTA_TEXT_LENGTH",
    "MAX_DURABLE_TASK_EVENT_DATA_BYTES",
    "MAX_EVENT_ARTIFACTS",
    "MAX_EVENT_TEXT_LENGTH",
    "MAX_LIFECYCLE_TEXT_JSON_BYTES",
    "MAX_PENDING_REVIEW_JSON_BYTES",
    "MAX_REVIEW_DECISIONS",
    "MAX_REVIEW_ITEMS",
    "MAX_SHORT_EVENT_TEXT_JSON_BYTES",
    "MAX_SHORT_EVENT_TEXT_LENGTH",
    "MAX_TASK_EVENT_CURSOR_LENGTH",
    "PUBLIC_ASSISTANT_DELTA_NODES",
    "PUBLIC_ASSISTANT_DELTA_PATH",
    "TASK_EVENT_CURSOR_VERSION",
    "TERMINAL_EVENT_TYPES",
    "InvalidTaskEventCursorError",
    "TaskEventLedger",
    "TaskEventSubscription",
    "TaskEventsUnavailableError",
    "TaskLifecycleEventType",
    "TaskRunMismatchError",
    "TaskStreamEvent",
    "artifact_event_data",
    "assistant_delta_from_stream_part",
    "decode_task_event_cursor",
    "encode_task_event_cursor",
    "lifecycle_event_data",
    "lifecycle_event_type",
    "normalize_task_event_text",
    "public_task_event_fingerprint",
]
